name: Update Rangers Schedule

on:
  schedule:
    # Runs every day at 5 AM ET (9 AM), Oct through May (NHL season)
    - cron: '0 9 * 1-5,10-12 *'
  workflow_dispatch: # Allows manual trigger
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Update schedule
      run: npm run update
      
    - name: Commit and push if changed
      run: |
        git config user.email github-actions
        git config user.name github-actions@github.com
        git add index.html
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update schedule - $(date)" && git push)
